spring.application.name=yahtzee_be

server.error.include-stacktrace=never

app.game.max-players=99


spring.datasource.url=jdbc:postgresql://localhost:5432/yahtzee
spring.datasource.username=postgres
spring.datasource.password=enca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# Abilita JWT da Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/yahtzee-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/yahtzee-realm/protocol/openid-connect/certs


#spring.security.oauth2.client.registration.keycloak.client-id=yahtzee-be-client
#spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOACK_CLIENT_SECRET}
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8081/realms/yahtzee-realm/protocol/openid-connect/token
#spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8081/realms/yahtzee-realm/protocol/openid-connect/auth
#spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8081/realms/yahtzee-realm/protocol/openid-connect/certs


