spring.application.name=yahtzee_be

server.error.include-stacktrace=never

app.game.max-players=99


spring.datasource.url=jdbc:postgresql://localhost:5432/yahtzee
spring.datasource.username=postgres
spring.datasource.password=enca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# Abilita JWT da Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/yahtzee-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/yahtzee-realm/protocol/openid-connect/certs


